---
title: "Plotly examples"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Loading data

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
#create subset 

data("instacart")

instacart = instacart %>% 
  select(order_dow, order_hour_of_day, aisle, product_name) %>%
  filter(aisle %in% c("fresh fruits")) %>% 
  mutate(order_dow = recode(order_dow, `0` = "Sunday", 
                            `1` = "Monday", 
                            `2` = "Tuesday", 
                            `3` = "Wednesday", 
                            `4` = "Thursday", 
                            `5` = "Friday", 
                            `6` = "Saturday")) %>%
  mutate(order_dow = factor(order_dow, levels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")))

```

#Plotly plots 

## bar chart 

```{r}

instacart %>% 
  group_by(product_name) %>% 
  summarize(n_obs = n()) %>% 
  filter(n_obs > 1000) %>%
  plot_ly(x = ~product_name, y = ~n_obs, type = "bar")

```
## boxplot 

```{r}
instacart %>% 
  group_by(product_name, order_dow) %>% 
  plot_ly(
    y = ~order_hour_of_day, x = ~order_dow, 
    type = "box", colors = "viridis")
```

## bar plot

```{r}
instacart %>%
  group_by(order_dow) %>% 
  summarize(number_products_ordered = n()) %>%
  plot_ly(x = ~order_dow, y = ~number_products_ordered, type = "scatter", mode = "lines")
```



